
#' Class ModelDefinition (and methods)
#'
#' @description This class must be used to create the models
#' used by your programs.
#' 
#'
#' @section Fields:
#' \describe{
#'
#' \item{\code{table}:}{Object of class \code{"character"}, the name of
#' the table. This field will be used to determine the name of the
#' resulting generated class}
#'
#' \item{\code{fields}:}{Object of class \code{"list"}, a named list.
#' The names are the fields of the table and the values are the SQL type
#' of the field (REAL, BOOLEAN, INTEGER, BLOB, or TEXT)}
#'
#' \item{\code{fk}:}{Object of class \code{"list"}, a simple list.
#' It contains the name of the tables that needs to be references by
#' this table.
#' Mutual references create linkage table.
#' One-way references create an fk field, named table_name_id.
#' }
#'
#' }#'
#' @import RSQLite
#' @export ModelDefinition
#' @exportClass ModelDefinition
ModelDefinition <- setRefClass(
    "ModelDefinition",
    fields=c(
        table="character",
        fields="list",
        fk="list"
    )
)

#' Class ORM (and methods)
#'
#' ORM class is the main class of the orm package.
#' This is one of the only class that should be used by programmers
#'
#'
#' @export ORM
#' @exportClass ORM
ORM <- setRefClass(
    "ORM",
    fields=c(
        model_definitions_="list",
        model_objects_="list",
        connected_="logical",
        connection_="SQLiteConnection",
        database_path="character",
        request_pool="list",
        execution_context="list",
        DELETE_ALL_TABLES="character",
        IF_NO_EXISTS="character",
        CREATE_TABLE_TEMPLATE="character",
        CREATE_LINKAGE_TABLE_TEMPLATE="character",
        SELECT_WHERE_TEMPLATE="character",
        INSERT_WHERE_TEMPLATE="character",
        UPDATE_WHERE_TEMPLATE="character",
        FK_TEMPLATE="character",
        OPERATORS="list",
        LOGICAL_CONNECTORS="list",
        TABLE_FIELD_="refObjectGenerator",
        WHERE_CLAUSE_="refObjectGenerator"
    )
)

#' Class ModelMeta (and methods)
#'
#' @description This class is the super class of classes generated by
#' the model builder
#' 
#'
#' @section Fields:
#' \describe{
#'
#'     \item{\code{table}:}{
#'         Object of class \code{"character"}, the name of
#'         the table. This field will be used to determine the name of the
#'         resulting generated class
#'     '}
#'
#'     \item{\code{fields}:}{
#'         Object of class \code{"list"}, a named list.
#'         The names are the fields of the table and the values are the SQL type
#'         of the field (REAL, BOOLEAN, INTEGER, BLOB, or TEXT)
#'     '}
#'
#'     \item{\code{fk}:}{
#'         Object of class \code{"list"}, a simple list.
#'         It contains the name of the tables that needs to be references by
#'         this table.
#'         Mutual references create linkage table.
#'         One-way references create an fk field, named table_name_id.
#'     }
#'
#' }
ModelMeta <- setRefClass(
    "ModelMeta",
    fields=c(
        modified__="list",
        sql_model__="ModelDefinition",
        table__="character",
        orm__="ORM",
        model_name__="character",
        fields__="list",
        id="numeric"
    )
)