#' 
#' @import DBI
#' @importFrom methods selectMethod setRefClass is
#' 
NULL


#' 
#' @export MANY_TO_MANY
MANY_TO_MANY <- 1

#' 
#' @export MANY_TO_ONE
MANY_TO_ONE <- 2

#' 
#' @export ONE_TO_MANY
ONE_TO_MANY <- 3

#' 
#' @export POSTGRES
POSTGRES <- "POSTGRES"

#' 
#' @export SQLITE
SQLITE <- "SQLITE"

#' 
#' @export MARIADB
MARIADB <- "MARIADB"

#' 
#' @export MYSQL
MYSQL <- "MYSQL"

#' 
#' @export NO_DBMS
NO_DBMS <- "NO_DBMS"

#' 
#' @export DBMS_LIST
DBMS_LIST <- c(
  POSTGRES,
  SQLITE,
  MARIADB,
  MYSQL,
  NO_DBMS
)

#' 
#' @export DBMS_NAMES
DBMS_NAMES <- list()
DBMS_NAMES[[POSTGRES]] <- "POSTGRES"
DBMS_NAMES[[SQLITE]] <- "SQLITE"
DBMS_NAMES[[MARIADB]] <- "MARIADB"
DBMS_NAMES[[MYSQL]] <- "MYSQL"
DBMS_NAMES[[NO_DBMS]] <- "NO_DBMS"

#' 
#' @export DBMS_DRIVER
DBMS_DRIVER <- list()
DBMS_DRIVER[[POSTGRES]] <- "Postgres"
DBMS_DRIVER[[SQLITE]] <- "SQLite"
DBMS_DRIVER[[MARIADB]] <- "MariaDB"
DBMS_DRIVER[[MYSQL]] <- "MySQL"
DBMS_DRIVER[[NO_DBMS]] <- "NO_DBMS"

#' 
#' @export DBMS_PORT_MAPPING
DBMS_PORT_MAPPING <- list()
DBMS_PORT_MAPPING[[POSTGRES]] <- 5432
DBMS_PORT_MAPPING[[SQLITE]] <- -1
DBMS_PORT_MAPPING[[MARIADB]] <- 3306
DBMS_PORT_MAPPING[[MYSQL]] <- 3306
DBMS_PORT_MAPPING[[NO_DBMS]] <- -1

#' 
#' @export DBMS_PACKAGES
DBMS_PACKAGES <- list()
DBMS_PACKAGES[[POSTGRES]] <- "RPostgres"
DBMS_PACKAGES[[SQLITE]] <- "RSQLite"
DBMS_PACKAGES[[MARIADB]] <- "RMariaDB"
DBMS_PACKAGES[[MYSQL]] <- "RMySQL"
DBMS_PACKAGES[[NO_DBMS]] <- NA

#' @export
DEFAULT_TYPE_MAPPING <- list(
  numeric="INTEGER",
  logical="BOOLEAN",
  character="TEXT",
  double="FLOAT",
  blob="BLOB",
  POSIXct="DATE",
  object="OBJECT"
)

#' @export
TYPES_MAPPINGS <- list()
TYPES_MAPPINGS[[POSTGRES]] <- DEFAULT_TYPE_MAPPING
TYPES_MAPPINGS[[SQLITE]] <- DEFAULT_TYPE_MAPPING
TYPES_MAPPINGS[[MARIADB]] <- DEFAULT_TYPE_MAPPING
TYPES_MAPPINGS[[MYSQL]] <- DEFAULT_TYPE_MAPPING
TYPES_MAPPINGS[[NO_DBMS]] <- DEFAULT_TYPE_MAPPING


#' @export
DEFAULT_CONNECTION_PARAMETERS <- list(
  host="localhost",
  user="",
  password="",
  database="",
  flags=0
)

#' @export
DEFAULT_CO_PARAMS <- list()

DEFAULT_CO_PARAMS[[POSTGRES]] <- DEFAULT_CONNECTION_PARAMETERS
DEFAULT_CO_PARAMS[[POSTGRES]]$port <- DBMS_PORT_MAPPING[[POSTGRES]]

DEFAULT_CO_PARAMS[[SQLITE]] <- DEFAULT_CONNECTION_PARAMETERS
DEFAULT_CO_PARAMS[[SQLITE]]$port <- DBMS_PORT_MAPPING[[SQLITE]]

DEFAULT_CO_PARAMS[[MARIADB]] <- DEFAULT_CONNECTION_PARAMETERS
DEFAULT_CO_PARAMS[[MARIADB]]$port <- DBMS_PORT_MAPPING[[MARIADB]]

DEFAULT_CO_PARAMS[[MYSQL]] <- DEFAULT_CONNECTION_PARAMETERS
DEFAULT_CO_PARAMS[[MYSQL]]$port <- DBMS_PORT_MAPPING[[MYSQL]]

DEFAULT_CO_PARAMS[[NO_DBMS]] <- DEFAULT_CONNECTION_PARAMETERS
DEFAULT_CO_PARAMS[[NO_DBMS]]$port <- DBMS_PORT_MAPPING[[NO_DBMS]]

#' @export
INNER_JOIN <- 1

#' @export
OUTER_JOIN <- 2

#' @export
LEFT_OUTER_JOIN <- 3

#' @export
RIGHT_OUTER_JOIN <- 4

